name: LPMCNavigator
main: me.Mentioum.LPMCNavigator.LPMCNavigator
version: 0.21
authors: [Mentioum]
description: >
             LPMCNavigator- Helping you find your way back to the places you have been before.
commands:
   navigate:
     description: Toggles compass navigation on and off.
     usage: /<command>
     aliases: [nav, navi, navigation, nv, navigator]